source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

gem "jekyll-theme-cayman"

gem "webrick", "~> 1.7"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"
  gem "jekyll-seo-tag"
end
